

import { useState, useEffect } from "react";

export function Body() {
    const [user, setUser] = useState(null);

    useEffect(() => {
        // Retrieve and parse the stored user data
        const storedUser = localStorage.getItem("user");
        if (storedUser) {
            try {
                const parsedUser = JSON.parse(storedUser);
                if (parsedUser && parsedUser.name) {
                    setUser(parsedUser);
                } else {
                    console.warn("Invalid user data in localStorage.");
                }
            } catch (error) {
                console.error("Error parsing user data from localStorage:", error);
            }
        }
    }, []);

    return (
        <div
            className="fixed top-16 left-28 right-3 bottom-5 z-50 bg-white rounded-tl-[30px] rounded-tr-[30px] rounded-bl-[30px] rounded-br-[30px] p-10 overflow-hidden"
        >
            {/* Content inside the curved area */}
            <p className="text-4xl font-bold text-black mb-5">
                Hi {user?.name || "Guest"}!
            </p>
            <div className="h-16 w-44 border border-gray-300 rounded-2xl flex bg-gradient-to-r from-cyan-200 to-blue-200">
            <button className="text-xl m-auto text-gray-700 font-medium">CREATE SPLIT</button>
            </div>

            <div className="overflow-y-auto h-full pr-4">
                {/* Add your dashboard cards, stats, or graphs here */}
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Temporibus laborum id ab earum, obcaecati quidem, consequuntur natus at sequi eaque voluptatem. Officiis vel praesentium excepturi impedit suscipit minima quod recusandae.
            </div>
        </div>
    );
}
